name: mastito
description:
meta_description: ""

markdown: kramdown

gems: [jekyll-paginate]

paginate: 20
paginate_path: "/blog/page:num/"
baseurl: /
domain_name: 'http://mastito03.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://mastito03.github.io'
author:         'Benedictus Arya'
authorTwitter:  #'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
            footer: true
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
            footer: true
            profile: false
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
            footer: true
